lambda:
  name: sso-api
  handler: app.handler
  runtime: python3.8
  timeout: 10
  memorySize: 128
  logsRetention: 14
  vpc:
    subnetIds:
      - subnet-05fd86470c50b4557
    securityGroupIds:
      - sg-080dd88c1838b1934
